## Add game
POST http://localhost:8080/games/game
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "userId": 1,
  "name": "Test game",
  "description": "Super fun test game"
}

### Add client
POST http://localhost:8080/clients/client
Content-Type: application/json

{
  "clientUid": "testclient"
}

### Post new score
POST http://localhost:8080/scores/score
Content-Type: application/json

{
  "gameId": 1,
  "clientUid": "testclient",
  "score": 100
}

### Get score
GET http://localhost:8080/scores/score?gameId=1&clientUid=testclient


### Add another client
POST http://localhost:8080/clients/client
Content-Type: application/json

{
  "clientUid": "testclient2"
}

### Post another new score
POST http://localhost:8080/scores/score
Content-Type: application/json

{
  "gameId": 1,
  "clientUid": "testclient2",
  "score": 120
}


### Get best scores by game from best to worse order
GET http://localhost:8080/scores/bestByGame?gameId=1


### Get all provided game id's scores for provided client uid
GET http://localhost:8080/scores/forClient?clientUid=testclient&gameIds=1,2
