## Add game
POST http://localhost:8080/games/game
Content-Type: application/json

{
  "name": "Test game",
  "description": "Super fun test game"
}

### Add client
POST http://localhost:8080/clients/client
Content-Type: application/json

{
  "clientUid": "testclient2"
}


### Post new score
POST http://localhost:8080/scores/score
Content-Type: application/json

{
  "gameId": 1,
  "clientUid": "testclient",
  "score": 100
}

### Get score
GET http://localhost:8080/scores/score?gameId=1&clientUid=testclient
